packaging_format = 2

id = "tiddlywiki"
name = "TiddlyWiki"
description.en = "Non-linear personal web notebook"
description.fr = "Carnet Web personnel non linéaire"

version = "5.2.7~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "BSD-3-Clause"
website = "https://tiddlywiki.com/"
demo = "https://tiddlywiki.com/"
admindoc = "https://tiddlywiki.com/"
code = "https://github.com/Jermolene/TiddlyWiki5"

[integration]
yunohost = ">= 11.1.16"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]

    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, TiddlyWiki will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, TiddlyWiki sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["ar-PS", "ca-ES", "cs-CZ", "da-DK", "de-AT", "de-CH", "de-DE", "el-GR", "en-US", "es-ES", "fa-IR", "fr-FR", "he-IL", "hi-IN", "ia-IA", "it-IT", "ja-JP", "ko-KR", "nl-NL", "pa-IN", "pl-PL", "pt-BR", "pt-PT", "ru-RU", "sk-SK", "sl-SI", "sv-SE", "zh-CN", "zh-Hans", "zh-Hant", "zh-HK", "zh-TW"]
    default = "en-US"

[resources]
        [resources.sources.main]
        url = "https://github.com/Jermolene/TiddlyWiki5/archive/v5.2.7.tar.gz"
        sha256 = "8db7e0a196f6afe311b0c4f5fd7ae36ad56ef31315480ae511f968691c3870ec"
        autoupdate.strategy = "latest_github_tag"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
