packaging_format = 2

id = "tiddlywiki"
name = "TiddlyWiki"
description.en = "Non-linear personal web notebook"
description.fr = "Carnet Web personnel non linéaire"

version = "5.2.5~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "BSD-3-Clause"
website = "https://tiddlywiki.com/"
demo = "https://tiddlywiki.com/"
admindoc = "https://tiddlywiki.com/"
code = "https://github.com/Jermolene/TiddlyWiki5"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "200M"
ram.runtime = "50M"

[install]
    [install.warning]
    ask.en = "It is important that you regularly backup your notes (tiddlers) locally befor upgrading the app.\nClick on the cloud icon -> `Save snapshot for offline use`\nTo restore a local backup to the server, drag and drop your tiddlers backup file into your TiddlyWiki page."
    ask.fr = "Il est important que vous sauvegardiez régulièrement vos notes (tiddlers) localement avant de mettre à jour l'application.\nCliquez sur l'icône cloud -> `Enregistrer l'instantané pour une utilisation hors ligne`\nPour restaurer une sauvegarde locale sur le serveur, faites glisser et déposez votre fichier tiddler dans votre page TiddlyWiki."
    type = "display_text"

    [install.domain]
    type = "domain"
    full_domain = true

    [install.init_main_permission]
    help.en = "If enabled, TiddlyWiki will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, TiddlyWiki sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "string"
    choices = ["ar-PS", "ca-ES", "cs-CZ", "da-DK", "de-AT", "de-CH", "de-DE", "el-GR", "en-US", "es-ES", "fa-IR", "fr-FR", "he-IL", "hi-IN", "ia-IA", "it-IT", "ja-JP", "ko-KR", "nl-NL", "pa-IN", "pl-PL", "pt-BR", "pt-PT", "ru-RU", "sk-SK", "sl-SI", "sv-SE", "zh-CN", "zh-Hans", "zh-Hant", "zh-HK", "zh-TW"]
    default = "en-US"

[resources]
        [resources.sources.main]
        url = "https://github.com/Jermolene/TiddlyWiki5/archive/v5.2.5.tar.gz"
        sha256 = "e2b131fa9700e58e88f92f236c362631f7c4ecce0eea2969c1a7a843f711440e"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
