test_format = 1.0

[default]

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.2e9f4ef4.name = "Upgrade from 5.2.3"
